[wasm] Make LimitsByte::is_shared() work in GCC
Importing a shared WebAssembly memory currently fails under gcc with

LinkError: ...mismatch in shared state of memory, declared = 0,
imported = 1

Since SharedFlag is `enum class : bool`, due to
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96496, gcc currently
incorrectly truncates the integer instead of converting it into
boolean, so 0x3 ends up being converted to SharedFlag::kNo.
This patch works around it with an explicit conversion.